# Generated by Django 5.1.1 on 2024-09-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificdateavailabilityslot',
            name='date',
        ),
    ]
