# Generated by Django 5.1.1 on 2024-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_remove_specificdateavailabilityslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificdateavailabilityslot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specificdateavailabilityslot',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
